CDCgov/NEDSS-Helm

- charts/patient-search/values-demo.yaml
Updates the Patient Search version to [46ec9cd](https://github.com/CDCgov/NEDSS-Modernization/commit/46ec9cdc0860674c8380278f47a5925c8f07d56e) for the Demo environment.
> Update demo/patient-search to 46ec9cd

- charts/nifi/values-int1.yaml
Requesting deployment of the `1.19.0-SNAPSHOT.43ae4c5` NiFi container to INT1.
> [INT1] Updates NiFi version to 1.19.0-SNAPSHOT.43ae4c5

- charts/elasticsearch/values-dev.yaml
- charts/modernization-api/values-dev.yaml
- charts/nifi/values-dev.yaml
Limit resources to containers deployed in dev to prevent errors. This can sit in PR until approved by other teams through jira.
> limit resources

- charts/nbs-gateway/templates/deployment.yaml
- charts/nbs-gateway/values-auto.yaml
- charts/nbs-gateway/values-int1.yaml
- charts/nbs-gateway/values.yaml
Updates the Page Builder service to point to the Page Builder API container. 
* Dependent on classic redirect library being added to Page builder in upcoming PR.
> Allow PageBuilder to handle redirections

- charts/modernization-api/templates/deployment.yaml
- charts/modernization-api/values-int1.yaml
- charts/modernization-api/values-test2.yaml
- charts/modernization-api/values.yaml
- charts/nbs-gateway/templates/deployment.yaml
- charts/nbs-gateway/values-int1.yaml
- charts/nbs-gateway/values-test2.yaml
- charts/nbs-gateway/values.yaml
Adds the following feature flags to the configuration passed to the nbs-gateway and modernization-api at startup.
The intent is to allow the feature flagging of the `Page Library` and `Page Management` screens.
```
pageBuilder:
page:
library:
enabled: "true"
management:
enabled: "true"
```
> Add page library, management feature flags for page builder

- charts/modernization-api/values-test2.yaml
- charts/nbs-gateway/values-test2.yaml
Release 7.2 will include the PageBuilder Page Library. This PR enables the Page Library while keeping the management screens disabled.
> Update test2 to enable page builder library

- charts/modernization-api/values-test2.yaml
- charts/nbs-gateway/values-test2.yaml
- charts/page-builder-api/values-test2.yaml
Deploy `1.0.1-TEST.ac01645` modernization-api, page-builder-api, nbs-gateway to test2.
This is done manually due to an issue with the auto generated PRs that will be resolved.
> Deploy new containers to test2

- charts/modernization-api/values-test2.yaml
- charts/nbs-gateway/values-test2.yaml
The PageBuilder Page Library will no longer be included in the 7.2 release. This PR updates the flags to disable this feature in the test environment.
> Disables PageBuilder in test2 env

- charts/modernization-api/values-test2.yaml
- charts/nbs-gateway/values-test2.yaml
We are yet again delaying the release of page builder and excluding it from release 7.2.2. 
This PR disables the page builder features in the test environment by reverting the commit that enabled them.
This reverts commit 420995716be0de69dd084ba58ea089e4895b80ee.
> Disable PB in test 

- charts/modernization-api/values-feature.yaml
- charts/nbs-gateway/values-feature.yaml
- charts/page-builder-api/values-feature.yaml
Updates the feature environment with the current `int1` containers for 
* modernization-api
* nbs-gateway
* page-builder-api
Enables Page Management `Edit` feature flag.
> Update feature to current int1 containers. Enable edit in page builder

- charts/modernization-api/templates/ingress.yaml
- charts/nginx-ingress/values.yaml
This fix is required to get reports functioning. Once this is merged, we will need to update all ingress deployments to allow configuration snippets.
> allow x-frame-options for classic app iframes

- charts/nbs-gateway/values-fts2.yaml
Deploys a potential fix to the nbs-gateway container to allow connection to an ALB with security policy: `ELBSecurityPolicy-TLS13-1-2-2021-06`
> Set image tag for nbs-gateway in fts-2

- charts/modernization-api/templates/deployment.yaml
- charts/modernization-api/values.yaml
- charts/nbs-gateway/templates/deployment.yaml
- charts/nbs-gateway/values.yaml
- charts/page-builder-api/templates/deployment.yaml
- charts/page-builder-api/values.yaml
Adds the ability to define an external OIDC issuer uri.  If `oidc.uri` is not present or blank in the values file the `oidc.uri` will be set to `https://{{ .Values.ingressHost }}/auth/realms/nbs-users`
> OIDC defaults

- charts/keycloak/theme/nbs/login/login.ftl
Corrects the password reset email address to be `nbs@cdc.gov` in the keycloak login theme.
> [FIX] Corrects password reset email

- charts/modernization-api/templates/deployment.yaml
- charts/modernization-api/values-int1.yaml
- charts/modernization-api/values.yaml
Passes the extended patient create feature flag to the modernization-api container. 
Default value will be false.
Set value to true in the int1 environment
> Extended patient create feature flag

- charts/modernization-api/templates/deployment.yaml
- charts/modernization-api/values.yaml
- charts/nbs-gateway/templates/deployment.yaml
- charts/nbs-gateway/values.yaml
Adds feature flags for the modernized patient profile.  
When the `patient.profile.enabled` feature flag is enabled for the `nbs-gateway` any routes that lead to the NBS6 patient profile are replaced with redirects to the modernized patient profile.  The flag is defaulted to `false`.
When the `patient.profile.enabled` feature flag is enabled for the `modernization-api` the modernized patient profile is shown when patient search results are clicked or after a new patient is added.  The flag is defaulted to `false`.
The code changes that use these flags has not been merged and will have no affect until those changes are deployed.  There will be a follow up PR to enable these flags in the INT1 environment.
> [CNFT1-3519] patient profile feature flag

- charts/debezium-srte/.helmignore
- charts/debezium-srte/Chart.yaml
- charts/debezium-srte/readme.md
- charts/debezium-srte/templates/NOTES.txt
- charts/debezium-srte/templates/_helpers.tpl
- charts/debezium-srte/templates/configmap.yaml
- charts/debezium-srte/templates/deployment.yaml
- charts/debezium-srte/templates/ingress.yaml
- charts/debezium-srte/templates/service.yaml
- charts/debezium-srte/values-azure.yaml
- charts/debezium-srte/values-dts1.yaml
- charts/debezium-srte/values-feature.yaml
- charts/debezium-srte/values-int1.yaml
- charts/debezium-srte/values-test1.yaml
- charts/debezium-srte/values.yaml
We want to enable Change Data Capture in SRTE database tables and thus, creating a new chart for it. This change is already tested in local.
> Adding debezium chart for SRTE database

- charts/modernization-api/values.yaml
I am removing the default values of properties that deal with external  services from the `modernization-api` configuration so that they are in one place in the helm charts.  
The change from `https://us.posthog.com` to `https://us.i.posthog.com` is intentional, the host name for capturing events was changed in the documentation.
> moves the default value of the analytics host to helm charts

- charts/data-processing-service/Chart.yaml
- charts/data-processing-service/values.yaml
added placeholders in values file
> this was a new container and not in the process for updates

- charts/debezium/values-dts1.yaml
- charts/debezium/values-feature.yaml
- charts/debezium/values-int1.yaml
- charts/debezium/values-test1.yaml
- charts/debezium/values.yaml
We need to a new table from odse `CN_transportq_out` to debezium source connector config that is required for NNDSS Rhapsody route replacement service.
> Adding CN_transportq_out to debezium CDC

- charts/data-processing-service/values.yaml
this should prevent error on helm install and these values will be needed in next release
> added placeholder for srte in data-processing-service

- charts/modernization-api/templates/deployment.yaml
- charts/modernization-api/values.yaml
- charts/nbs-gateway/templates/deployment.yaml
- charts/nbs-gateway/values.yaml
- charts/page-builder-api/templates/deployment.yaml
- charts/page-builder-api/values.yaml
Adds configuration for setting the timezone at deployment time for the JVM of the `modernization-api`, `page-builder-api` and `nbs-gateway` containers.  The default value is set in `values.yaml` for each service as `UTC`.
The `America/Denver` timezone would be used for containers that need to be set to the Mountain Time Zone.
[MU-34](https://cdc-nbs.atlassian.net/browse/MU-34)
> [MU-34] adds timezone configurations to spring containers

- charts/nbs6/templates/ingress-cached.yaml
- charts/nbs6/values.yaml
> ingress updates

- charts/modernization-api/templates/deployment.yaml
- charts/modernization-api/values-int1.yaml
- charts/modernization-api/values.yaml
Adds two new `modernization-api` configurations.
- `ui.defaults.sizing` to allow the configuration of the default sizing of components.  The default is `medium` with INT1 being set to `small`
- `ui.features.patient.search.filters.enabled` to enables access to modernized Patient search filters.  The default is `false` with the feature being enabled in INT1.
Verified defaults locally by executing
`helm template --debug ./modernization-api -f ./modernization-api/values.yaml `
Verified INT1 specific settings locally by executing
`helm template --debug ./modernization-api -f ./modernization-api/values-int1.yaml `
> [CNFT1-3778] Component size configuration and patient search filter feature

- charts/sas-linux/templates/cron.yaml
Added spec to sas to prevent concurrent runs on cron jobs under the cron job '{{ include "sas-linux.name" . }}-cron-etl' which could have unintended consequences. Under normal circumstances there is sufficient time between jobs that they should never overlap, so this is a precautionary measure.
> limit sas to 1 concurrent job

- charts/modernization-api/values-test2.yaml
Turns off the Patient Search Filters in the TEST environment to match the list of features that will be released in `7.8.3`.  Patient Search Filters will be part of the next release.
> [Feature] Patient Search Filters off

- charts/modernization-api/values-test2.yaml
Overrides the default component sizing in TEST to allow QA to verify the `small` variant UI components.
> [TEST] Set component sixingsizing to small

- charts/investigation-reporting-service/values-int1.yaml
- charts/post-processing-reporting-service/values-test1.yaml
```  eventMetricEnable: "true"
dTbHivEnable: "true"
morbReportDmEnable: "true"
invSummaryDmEnable: "true"
summaryReportEnable: "true"
aggregateReportEnable: "true"```
> Enable the RTR service flags for the 4.9.1 release

- charts/record-linker-api/templates/deployment.yaml
Removes `serviceAccountName` reference from deployment.yaml for record-linker-api.
> Removes serviceAccount reference from deployment.yaml

- charts/liquibase/values-dts1.yaml
- charts/liquibase/values-feature.yaml
- charts/liquibase/values-int1.yaml
- charts/liquibase/values-test1.yaml
- charts/liquibase/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
> Sgz remove liquibase linkerd

- charts/modernization-api/templates/deployment.yaml
- charts/modernization-api/values-int1.yaml
- charts/modernization-api/values.yaml
In order to add navigable links to the UI for a user to manage the deduplication configuration, the System Management page needs to be modernized. [CND-320](https://cdc-nbs.atlassian.net/browse/CND-320?atlOrigin=eyJpIjoiZjc2Zjc3ZTc1NDg1NDI1ZjljMDUwNThhOGZhOTIyYTkiLCJwIjoiaiJ9)
> Flags for system management

- .gitignore
- argocd/Chart.yaml
- argocd/templates/investigation-service.yaml
- argocd/templates/post-processing-service.yaml
- charts/keycloak/templates/deployment.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
> Release-7.9.3.1

- charts/rtr/Chart.yaml
- charts/rtr/templates/_helpers.tpl
- charts/rtr/templates/deployment.yaml
- charts/rtr/templates/hpa.yaml
- charts/rtr/templates/service.yaml
- charts/rtr/templates/serviceaccount.yaml
- charts/rtr/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
> added consolidated rtr helm chart

- argocd/templates/elasticsearch.yaml
- argocd/templates/nifi.yaml
- argocd/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
> Added values for Nifi and Elasticsearch

- .github/workflows/trivy-helm-scan.yaml
Adding small change to include Argocd to path.
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```    
4. values.yaml is annotated to include parameter description and format as appropriate.
- values.yaml is …
> add argocd to path

- charts/rtr/values-dts1.yaml
- charts/rtr/values-dummy.yaml
- charts/rtr/values.yaml
Configures prometheus scrapers for RTR java services.
Jira ticket: [CNDE-3125](https://cdc-nbs.atlassian.net/browse/CNDE-3125)
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
> CNDE-3125: Prometheus metrics to RTR services

- charts/rtr/templates/deployment.yaml
- charts/rtr/values-dts1.yaml
- charts/rtr/values-dummy.yaml
- charts/rtr/values.yaml
Updates the feature flag to optionally skip processing of PHCF datamart in the RTR pre-processing services.
Jira ticket: [CNDE-3138](https://cdc-nbs.atlassian.net/browse/CNDE-3138)
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```    
3. **Do not include secret values anywhere in a Helm chart, take special care when …
> CNDE-3138: Add/update feature flag to disable processing PHCF datamart
