charts/elasticsearch/templates/deployment.yaml, charts/elasticsearch/templates/es-pv-claim.yaml, charts/elasticsearch/templates/gp-es.yaml, charts/elasticsearch/templates/storageclass.yaml, charts/elasticsearch/values-dev.yaml
=> Revert "CNPT-1069: Use EFS for Elasticsearch"

charts/patient-search/values-auto.yaml, charts/patient-search/values-dev.yaml
I am doing it just for Dev and Automation Sandbox initially.
=> switch to image tag main-93 for auto and dev environments.

charts/patient-search/values-demo.yaml, charts/patient-search/values-test.yaml, charts/patient-search/values-test2.yaml
Demo, test and test 2 envs changed.
=> Changed to main-93 tag for demo and test envs

README.md, charts/README.md, charts/common-asset-server/README.md, charts/elasticsearch-efs/README.md, charts/elasticsearch/README.md, charts/hybrid-integration/README.md, charts/kafka/README.md, charts/nginx-ingress/README.md, charts/nifi/README.md, charts/patient-search/README.md
Initial README.md files for first and second layer directories (minus Kafka). Readme files still need to be added for "Template" directories as well.
=> Cnpt 1151 readme additions

charts/nifi/values-demo.yaml, charts/patient-search/values-demo.yaml
Updates the demo environment to patient-search [1.0.1-SNAPSHOT.d92dde4](https://github.com/CDCgov/NEDSS-Modernization/commit/d92dde48db53a831d834ad3be7325f128d9c97d9) and NiFi [1.19.0-SNAPSHOT.f3b68e0](https://github.com/CDCgov/NEDSS-Modernization/commit/f3b68e038cc6d71cf84491847e05a87b2e55cb4d)
=> Feature Team 1 / Sprint 24 Demo deployment

charts/hybrid-integration/values-auto.yaml, charts/hybrid-integration/values-data-dev.yaml, charts/hybrid-integration/values-demo.yaml, charts/hybrid-integration/values-dev.yaml, charts/hybrid-integration/values-test.yaml, charts/hybrid-integration/values-test2.yaml, charts/patient-search/templates/ingress.yaml
Please review and approve these changes. These are required for AddInvestigation to work on all envrionments.
=> Commented out /nbs/SelectCondition1.do condition

charts/patient-search/values-demo.yaml
Deploys [rc_20230803](https://github.com/CDCgov/NEDSS-Modernization/tree/rc_20230803) to the demo environment. 
Deployment approved for 08/08/2023 before 8 am
=> Deploy rc_20230803 to demo

charts/patient-search/values-demo.yaml
Reverts the DEMO environment to 1.0.1-DEMO.f205cc0
=> Revert DEMO to 1.0.1-DEMO.f205cc0

charts/nifi/values-test.yaml
Updates NiFi to 1.19.0-SNAPSHOT.ff8163b in TEST
=> Updates NiFi to 1.19.0-SNAPSHOT.ff8163b in TEST

charts/dataingestion-service/templates/storageclass.yaml, charts/dataingestion-service/values-dataingestion-dev.yaml
Updated values-dataingestion-dev.yaml and storageclass.yaml files.
=> Updated for efs storage class.

charts/modernization-api/values-test.yaml, charts/nbs-gateway/values-test.yaml, charts/nifi/values-test.yaml
QA has asked that TEST1 be the reference environment for RC_20230906.
=> Request TEST deployment

charts/dataingestion-service/values-dataingestion-dev.yaml
Added prometheus.io/scheme: "https" in values-dataingestion-dev.yaml as suggested by Ozair.
=> Dataingestion prometheus https

charts/modernization-api/templates/ingress.yaml, charts/modernization-api/values-auto.yaml, charts/modernization-api/values-demo.yaml, charts/modernization-api/values-fed.yaml, charts/modernization-api/values-int1.yaml, charts/modernization-api/values-newdemo.yaml, charts/modernization-api/values-test.yaml, charts/modernization-api/values-test2.yaml, charts/modernization-api/values.yaml, charts/page-builder-api/.helmignore, charts/page-builder-api/Chart.yaml, charts/page-builder-api/README.md, charts/page-builder-api/templates/NOTES.txt, charts/page-builder-api/templates/_helpers.tpl, charts/page-builder-api/templates/deployment.yaml, charts/page-builder-api/templates/hpa.yaml, charts/page-builder-api/templates/service.yaml, charts/page-builder-api/templates/serviceaccount.yaml, charts/page-builder-api/templates/tests/test-connection.yaml, charts/page-builder-api/values-auto.yaml, charts/page-builder-api/values-dev.yaml, charts/page-builder-api/values.yaml
Changes required for pagebuilder.
Expected changes to environments not needing pagebuilder functionality: no functional changes, a few new inputs that do not affect runtime. Will not affect the current demo environment.
Changes include- 1 route in modernization-api and a new flag for page-builder. The page-builder container itself.
=> pagebuilder chagnes for dev

charts/dataingestion-service/templates/deployment.yaml, charts/dataingestion-service/values-int1.yaml
Changed the server port from 8080 to 8081 to resolve the conflict with the Prometheus service.
And to deploy the latest code in the int1 environment.
=> The server port changed to 8081 and to deploy latest code.

charts/dataingestion-service/templates/ingress.yaml, charts/dataingestion-service/values-test2.yaml
=> Updated for test2 deployment

charts/dataingestion-service/templates/ingress.yaml, charts/dataingestion-service/values-dev.yaml, charts/dataingestion-service/values-int1.yaml, charts/dataingestion-service/values-test2.yaml
Removed repo name from values file, Ingress path updated, and latest image named used.
=> Removed repo name from values file.

charts/page-builder-api/values-int1.yaml
Adds INT1 values for pagebuilder.
=> Add int1 deployment for pagebuilder

charts/modernization-api/values-int1.yaml, charts/page-builder-api/values-int1.yaml
=> Update PB - Modernization API image

charts/nbs-gateway/values-int1.yaml
Updates nbs-gateway image to dev value
=> Update nbs-gateway image

charts/dataingestion-service/values-dev.yaml, charts/dataingestion-service/values-int1.yaml, charts/dataingestion-service/values-test2.yaml
Removed hard code db, kafka values and moved them into --set param.
=> Removed hard code db, kafka values

charts/nbs-gateway/templates/deployment.yaml, charts/nbs-gateway/values-auto.yaml, charts/nbs-gateway/values-int1.yaml, charts/nbs-gateway/values.yaml
Updates the args for nbs-gateway to include the Page Builder configurations. 
Sets the default to `false` with the int1 environment set to `true`
=> Add config for nbs-gateway to enable Page Builder

charts/modernization-api/values-test2.yaml
Sets the version of the `modernization-api` container to 1.0.1-RC_20231031.8e6aa01 in TEST
=> Deploy 1.0.1-RC_20231031.8e6aa01 to TEST

charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/values.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/values.yaml
=> added repository and tag value to each values file

charts/nbs-gateway/templates/deployment.yaml, charts/nbs-gateway/values-auto.yaml, charts/nbs-gateway/values-int1.yaml, charts/nbs-gateway/values.yaml
Previous PR should not have been merged quite yet. My mistake.
This reverts commit b3caf94092e15a5732692694c4b5b8496dcbf4df.
=> Revert "Point pagebuilder redirects to pagebuilder API (#170)"

charts/modernization-api/values-test2.yaml, charts/nbs-gateway/values-test2.yaml
Requests deployment of the release candidate for `release-7.1.1`.
- `nbs-gateway:1.0.1-TEST.57dfc7e`
- `modernization-api:1.0.1-TEST.57dfc7e`
=> Requests deployments for nbs-gateway and modernization-api

charts/modernization-api/values-feature.yaml, charts/nbs-gateway/values-feature.yaml, charts/page-builder-api/values-feature.yaml
Deploys the latest `modernization-api`, `nbs-gateway`, and `pagebuilder-api` containers to feature environment.
Updates PageBuilder feature flags to have `management` turned off for `feature` environment.
=> Update `feature` environment

charts/modernization-api/values-feature.yaml, charts/page-builder-api/values-feature.yaml
Deploys the updated modernization-api and page-builder container into the feature environment for testing.
=> Deploy latest to feature

charts/dataingestion-service/templates/deployment.yaml, charts/dataingestion-service/values-fts2.yaml
To deploy DI app in FTS2 environment for testing Keycloak implementation.
=> Di auth keycloak fts2

charts/dataingestion-service/values-fts2.yaml
To deploy the old auth code in the fts2 env for testing.
=> Merging main code into branch.

charts/modernization-api/values-int1.yaml, charts/nbs-gateway/values-int1.yaml
Reverts the previous PR's change to disable the edit page.
=> Enable page edit in int1

charts/dataingestion-service/values-dev.yaml, charts/dataingestion-service/values-fts1.yaml, charts/dataingestion-service/values-int1.yaml, charts/dataingestion-service/values-test2.yaml, charts/dataingestion-service/values.yaml
Added authUri: "" in all the values to be consistent.
=> Added authUri: "" , which will be used for keycloak implementation.

charts/modernization-api/values-feature.yaml, charts/nbs-gateway/values-feature.yaml, charts/page-builder-api/values-feature.yaml
Updates the feature environment to match int1
Enables `Page create` within feature environment.
=> Update feature env

.github/workflows/create-github-draft-release.yaml
Creates the workflow for automated draft releases. It is a manual trigger through the Actions tab.
=> create draft release

charts/modernization-api/values-feature.yaml, charts/page-builder-api/values-feature.yaml
Deploys a couple of bug fixes into the feature environment.
=> Updates feature to current int1

charts/modernization-api/values-feature.yaml, charts/page-builder-api/values-feature.yaml
Deploys latest containers to feature
=> Update feature to latest int1 containers

charts/keycloak/README.md, charts/keycloak/nbs_keycloak_remove.sql
=> Cmoss update keycloak readme and add cleanup steps

charts/dataingestion-service/templates/deployment.yaml, charts/dataingestion-service/values-dev.yaml, charts/dataingestion-service/values-dts1.yaml, charts/dataingestion-service/values-fts1.yaml, charts/dataingestion-service/values-fts2.yaml, charts/dataingestion-service/values-int1.yaml, charts/dataingestion-service/values-test2.yaml
Removed the rsa private and public key params from the deployment.yaml and values files.
These params/values are not required after keycloak auth implementation.
rsa:
privateKey:
publicKey:
=> Removed rsa private and public key params.

charts/dataingestion-service/Chart.yaml, charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/Chart.yaml, charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/Chart.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml
updated app version and tag as per confluence table
=> updated app version and tag

charts/modernization-api/values-feature.yaml
Deploys a small bug fix with the create question form not resetting after question creation to feature
=> Deploy small bug fix

charts/modernization-api/values.yaml, charts/nbs-gateway/values.yaml
changed settings in values.yaml files to enable page-builder-api by default.  Will clean up install document for 7.3.1
=> enable page-builder-api

charts/modernization-api/values-feature.yaml, charts/nbs-gateway/values-feature.yaml, charts/page-builder-api/values-feature.yaml
Updates feature env to have the latest containers.
=> Update feature env to latest int

charts/modernization-api/values-feature.yaml, charts/page-builder-api/values-feature.yaml
Updates feature environment to latest in preparation of GDIT demo.
=> Update feature to latest

.github/workflows/create-github-draft-release.yaml
=> charts/nginx-ingress/values-* does not exist, removing exclusion to

.github/workflows/create-github-draft-release.yaml
double checked this existed but only really existed on my local machine. d'oh!
=> removed keycloak values-* exclusion

charts/modernization-api/values-feature.yaml, charts/page-builder-api/values-feature.yaml
update feature to latest page-builder and modernization-api
=> Feature update

charts/dataingestion-service/Chart.yaml, charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/Chart.yaml, charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/Chart.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml
updated for release from table
=> updated for 7.4.0 release

charts/nifi-efs/values.yaml, charts/page-builder-api/values.yaml
make more EXAMPLE keywords to make customization easier
=> Cmoss prep for 7.4.0 20240430

charts/dataingestion-service/values.yaml
making it easier to find what needs to change
=> added EXAMPLE keywords

charts/modernization-api/templates/ingress.yaml, charts/modernization-api/values-dts1.yaml, charts/modernization-api/values-int1.yaml, charts/modernization-api/values-test2.yaml, charts/modernization-api/values.yaml
=> Sgz update environments

charts/nbs-gateway/values.yaml
was updated in modernization-api but not gateway
=> this values file had not been updated with edit = true

charts/dataingestion-service/values-test2.yaml
To deploy the new image in the Test env, which has a fix for the issue in the demo environment.
=> New image tag for the test env deployment.

charts/dataingestion-service/Chart.yaml, charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/Chart.yaml, charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/Chart.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml
Updated release values files and charts
=> updating versions

charts/modernization-api/values-int1.yaml, charts/nbs-gateway/templates/deployment.yaml, charts/nbs-gateway/values-int1.yaml
Configures the `INT1` environment to display the new Welcome page and routes `/` to `/welcome`.  All other environments will use the default values that disable the Welcome page and routes `/` to `/nbs/login`
=> CNFT1-2327 welcome route feature flag

charts/dataingestion-service/Chart.yaml, charts/elasticsearch-efs/Chart.yaml, charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/Chart.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml
=> modified for 7.4.2

charts/dataingestion-service/Chart.yaml, charts/elasticsearch-efs/Chart.yaml, charts/keycloak/extra/NBS_Realm_with_DI_Client.json, charts/keycloak/extra/nbs-users-brute-force-protection.json, charts/modernization-api/Chart.yaml, charts/nbs-gateway/Chart.yaml, charts/nifi-efs/Chart.yaml, charts/page-builder-api/Chart.yaml
updated for 7.4.3, readded some json files to import after keycloak
The json for import are very large, they can be simplified next release
=> updated for 7.4.3, readded some json files to import after keycloak

charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml
v1.1.2 -> v1.1.3, had thought that tag had been updated.....
=> v1.1.2 -> v1.1.3

charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml
this should merge to release branch
=> sync tags with zip file

charts/modernization-api/values-int1.yaml, charts/nbs-gateway/values-test2.yaml
Enables the welcome page in the TEST environment and removes unused properties from the INT1 `modernization-api` values.
=> Enables the welcome page in the TEST environment

charts/keycloak/README.md, charts/keycloak/templates/deployment.yaml, charts/keycloak/templates/persistentvolumeclaim.yaml, charts/keycloak/templates/storageclass.yaml, charts/keycloak/values.yaml
Other themes could be added but need to persist so they are available with container restarts
=> Adding a persistent volume and preloading an NBS theme

charts/debezium/values-int1.yaml
Update the INT1 values file for the data reporting services
=> Cndit 1559: Update the INT1 values file for the data reporting services

charts/debezium/values-int1.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-int1.yaml
Updating the values-int1 for different data reporting services.
=> Cndit 1559: Updating the values-int1 for different data reporting services.

charts/nbs-gateway/values.yaml
=> Cmoss prep for 7.5.2

charts/debezium/values-test1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/kafka-connect-sink/values-test1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-test1.yaml
CNAT-242 : Add the values files for the RTR services to be deployed in Test environment.
=> CNAT-242 : Add the values files for the RTR services to be deployed in Test environment.

.github/workflows/create-github-draft-release.yaml
updated workflow with new containers, the naming convention on new containers is inconsistent so when fixed we will have to change again
=>  added new RTR containers to zip

charts/investigation-reporting-service/values-dts1.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-dts1.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-dts1.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-dts1.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-dts1.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-dts1.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml
Updating the image tags for the Data Real Time Reporting RTR services
=> Updating the image tags for the Data Real Time Reporting RTR services

charts/debezium/values.yaml, charts/liquibase/values.yaml
update a couple values files to be more templates with placeholders for easy editing
=> Cmoss 20240910 update rtr 4 release

charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
Update the images with the latest tags
=> Rolling out the latest changes for RTR in INT1 and TEST.

charts/liquibase/templates/deployment.yaml, charts/liquibase/values-dts1.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/liquibase/values.yaml
CNDIT-266: Liquibase service added scripts for classic RDB and migrated the RDB_Modern to its own logical structure.
=> CNDIT-266: Liquibase service added scripts for classic RDB and migrated the RDB_Modern to its own logical structure.

charts/modernization-api/values-test2.yaml
As part of the 7.7.0 Release candidate deployment to test, the feature flag for extended patient is being enabled for the TEST environment.
=> [Feature] Enables extended patient add in Test

charts/dataingestion-service/Chart.yaml, charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/Chart.yaml, charts/investigation-reporting-service/Chart.yaml, charts/ldfdata-reporting-service/Chart.yaml, charts/liquibase/Chart.yaml, charts/modernization-api/Chart.yaml, charts/nbs-gateway/Chart.yaml, charts/nifi-efs/Chart.yaml, charts/nnd-service/Chart.yaml, charts/nnd-service/values.yaml, charts/observation-reporting-service/Chart.yaml, charts/organization-reporting-service/Chart.yaml, charts/page-builder-api/Chart.yaml, charts/person-reporting-service/Chart.yaml, charts/post-processing-reporting-service/Chart.yaml
update values.yaml and Charts for 7.6.3
=> release 7.6.3

charts/dataingestion-service/Chart.yaml, charts/nnd-service/Chart.yaml
=> Cmoss 20241011 763 take2

charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
CNDIT-281: Promote the Data RTR bits witht the following tag in INT/TEST : `1.0.1-SNAPSHOT.7fabdf1`
=> CNDIT-281: Promote the Data RTR bits with the 7.7 release bits in INT/TEST 

charts/ldfdata-reporting-service/templates/service.yaml, charts/ldfdata-reporting-service/values-dts1.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values.yaml, charts/observation-reporting-service/templates/service.yaml, charts/observation-reporting-service/values.yaml, charts/organization-reporting-service/templates/service.yaml, charts/person-reporting-service/templates/service.yaml, charts/post-processing-reporting-service/templates/service.yaml
CNAT-288: Updating the service name for the ldf,observation, organization, person and post-processing reporting services.
=> CNAT-288: Updating the service name for the ldf,observation, organization, person and post-processing reporting services.

charts/nginx-ingress/values.yaml
updating nginx configmap with proxy-body-size annotations
=> updated nginx annotations

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
CNDE-1932: Upgrade RTR services in INT/TEST to tag `9f057cf`
=> CNDE-1932: Upgrade RTR services in INT/TEST to tag `9f057cf`

charts/nbs-gateway/values-int1.yaml
Updates the values file for the INT1 environment to enable the routing to modernized patient profile from links within NBS6.
=> Enable routing to the modernized patient profile from NBS6 in INT1

charts/nifi-efs/values-test2.yaml
deploy the same container tag in INT1 to TEST
=> Merge helm-update-nifi-1.19.0-SNAPSHOT.7775276 into main

charts/nbs6/Chart.yaml, charts/nbs6/templates/deployment.yaml, charts/nbs6/templates/ingress.yaml, charts/nbs6/templates/service.yaml, charts/nbs6/values.yaml, charts/sas-linux/Chart.yaml, charts/sas-linux/templates/deployment.yaml, charts/sas-linux/templates/service.yaml, charts/sas-linux/values.yaml
Please review the helm charts for NBS6 and SAS. I have tested these on Azure dev.
=> Initial revision for NBS6 and SAS-linux helm charts

charts/dataingestion-service/values-int1.yaml, charts/dataingestion-service/values-test2.yaml
Adding a new tag for INT1 and TEST env for a bug fix in the Data Ingestion service to push it to the upcoming release.
=> Data Ingestion tag update for INT1 and TEST 7.8.0

charts/debezium-srte/values-azure.yaml, charts/debezium-srte/values-dts1.yaml, charts/debezium-srte/values-feature.yaml, charts/debezium-srte/values-int1.yaml, charts/debezium-srte/values-test1.yaml, charts/debezium-srte/values.yaml
- Update some typo in the name
- Removed the table include list param
- Updated snapshot mode for DTS1 to test
=> Removed table include list and updated snapshot mode for SRTE

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
RTR liquibase tag update to 65da511
=> RTR update liquibase tag

charts/debezium-srte/values-azure.yaml, charts/debezium-srte/values-dts1.yaml, charts/debezium-srte/values-feature.yaml, charts/debezium-srte/values-int1.yaml, charts/debezium-srte/values-test1.yaml, charts/debezium-srte/values.yaml, charts/debezium/values-azure.yaml, charts/debezium/values-dts1.yaml, charts/debezium/values-feature.yaml, charts/debezium/values-int1.yaml, charts/debezium/values-test1.yaml, charts/debezium/values.yaml
Updated both debezium and debezium srte to add transform config for timezone changes.
=> Updated debezium transform config for timezone

charts/nbs6/templates/ingress.yaml
Fixes how annotations are read from values file
=> fix annotations read

charts/modernization-api/templates/deployment.yaml, charts/modernization-api/values-int1.yaml, charts/modernization-api/values.yaml
Enables the deduplication UI screens in the INT1 environment.
Requires: https://github.com/CDCgov/NEDSS-Modernization/pull/2171/ be merged first.
=> Add feature flag for deduplication screens

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
Rtr updates int test to tag 74a3bf1
=> Rtr updates int test to tag 74a3bf1

charts/liquibase/templates/deployment.yaml, charts/liquibase/values-dts1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/liquibase/values.yaml
CNDE-2181: Create a database connection for the SRTE database and update the deployment.yaml
=> CNDE-2181: Create a database connection for the SRTE database and update the deployment.yaml

charts/keycloak/extra/05-nbs-users-nnd-client.json, charts/keycloak/extra/06-nbs-users-srte-data.json, charts/keycloak/extra/07-nbs-users-data-compare-api.json, charts/nnd-service/values-dts1.yaml, charts/srte-data-service/values.yaml
fixing some json imports and srte (in development) values file
=> Cmoss prep for release7.8.2

charts/data-processing-service/templates/deployment.yaml, charts/data-processing-service/values-fts1.yaml
1. Adds modernized matching feature flag to data-processing-service.
2. Enables modernized matching in fts1
=> Data processing deduplication flag

charts/dataingestion-service/values-feature.yaml, charts/dataingestion-service/values-fts1.yaml
updates "FEATURE" environment data-ingestion-service container.
=> Update data ingestion feature

charts/modernization-api/values-test2.yaml
The new version of basic patient Data Entry will be enabled for the TEST environment to allow for release testing.
=> Enables the updated version of New patient Data entry in TEST

charts/modernization-api/values-int1.yaml, charts/modernization-api/values-test2.yaml, charts/modernization-api/values.yaml
- Enables the "New Patient" and "New Patient - extended" pages by default.
- Enables Patient search filters by default.
=> [Feature Flags] New patient pages enabled by default

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
CNAT-375: Update the RTR release tag
=>  CNAT-375: Update the RTR release tag

charts/data-processing-service/Chart.yaml, charts/dataingestion-service/Chart.yaml, charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/Chart.yaml, charts/investigation-reporting-service/Chart.yaml, charts/investigation-reporting-service/values.yaml, charts/ldfdata-reporting-service/Chart.yaml, charts/ldfdata-reporting-service/values.yaml, charts/liquibase/Chart.yaml, charts/liquibase/values.yaml, charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/Chart.yaml, charts/nifi-efs/values.yaml, charts/nnd-service/Chart.yaml, charts/nnd-service/values-dts1.yaml, charts/nnd-service/values.yaml, charts/observation-reporting-service/Chart.yaml, charts/observation-reporting-service/values.yaml, charts/organization-reporting-service/Chart.yaml, charts/organization-reporting-service/values.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml, charts/person-reporting-service/Chart.yaml, charts/person-reporting-service/values.yaml, charts/post-processing-reporting-service/Chart.yaml, charts/post-processing-reporting-service/values.yaml
prepping for draft release, chance of changes if table in confluence is incorrect
=> updated for 7.9.0

charts/investigation-reporting-service/values-dts1.yaml, charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/templates/deployment.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
CNDE-2459:Promoting the INT/TEST version from DTS1
=>  CNDE-2459:Promoting the INT/TEST version from DTS1

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml
CNAT-411: RTR Promotion to tag `1b950d5`
=> CNAT-411: RTR Promotion to tag `1b950d5`

charts/deduplication-api/values-int1.yaml
Updates deduplication-api container in INT1.
=> Update deduplication-api container

charts/nbs6/values.yaml
Adds parameters to values file that are now configurable as a result of new container build
=> update values to match latest container

charts/data-processing-service/Chart.yaml, charts/data-processing-service/values.yaml, charts/dataingestion-service/Chart.yaml, charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/Chart.yaml, charts/investigation-reporting-service/Chart.yaml, charts/investigation-reporting-service/values.yaml, charts/ldfdata-reporting-service/Chart.yaml, charts/ldfdata-reporting-service/values.yaml, charts/liquibase/Chart.yaml, charts/liquibase/values.yaml, charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/Chart.yaml, charts/nnd-service/Chart.yaml, charts/nnd-service/values.yaml, charts/observation-reporting-service/Chart.yaml, charts/observation-reporting-service/values.yaml, charts/organization-reporting-service/Chart.yaml, charts/organization-reporting-service/values.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml, charts/person-reporting-service/Chart.yaml, charts/person-reporting-service/values.yaml, charts/post-processing-reporting-service/Chart.yaml, charts/post-processing-reporting-service/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> updated for 7.9.1

charts/data-compare-api-service/values.yaml, charts/liquibase/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> Cmoss 20240416 cleanup examples - minor changes

.github/workflows/trivy-helm-scan.yaml
Updates broken upload action to use v3 version.
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```    
4. values.yaml is annotated to include parameter description and format as appropriate.
- values.yaml is …
=> update upload action

charts/record-linker-api/values-demo.yaml, charts/record-linker-api/values-int1.yaml, charts/record-linker-api/values-test1.yaml, charts/record-linker-api/values.yaml
Adds resource limit to RL helm chart
=> Add resource limit for RL service

charts/record-linker-api/templates/_helpers.tpl
Removes unnecessary entries from `_helpters.tpl` from record-linker-api
=> Remove unused helpers

charts/record-linker-api/templates/service.yaml
Removes https port from record-linker-api
=> Remove https port

charts/record-linker-api/templates/deployment.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> Update deployment.yaml - recordlinker

charts/cluster-autoscaler/values-placeholder.yaml
See added file, basically workflow removes values-<site>.yaml files and errors out if one does not exist in each directory specified
Will check workflow options as well
=> workaround to keep draft-release workflow uniform

charts/keycloak/extra/08-nbs-users-realm-MFA.json
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> New realm with MFA

charts/data-processing-service/values-int1.yaml, charts/deduplication-api/values-int1.yaml, charts/modernization-api/values-int1.yaml, charts/modernization-api/values.yaml, charts/record-linker-api/values-int1.yaml, charts/record-linker-api/values-test1.yaml
1. Updates the Record Linker version to v25.5.0
2. Enables some feature flags for INT1 environment
=> Update record linker version

charts/modernization-api/templates/deployment.yaml
Passes the merge ui flag to startup params for modernization-api.
=> Adds merge flag to modernization-api parameters. Default false

charts/data-processing-service/values-int1.yaml
Deploy latest data-processing-service container into INT1.
=> use latest data-processing-container

charts/deduplication-api/templates/deployment.yaml, charts/deduplication-api/values-int1.yaml, charts/deduplication-api/values.yaml
Adds the new configuration parameters from https://github.com/CDCgov/NEDSS-DataIngestion/pull/364 to the `deduplication-api`
=> Pass process parameters to deduplication-api

charts/deduplication-api/templates/deployment.yaml
Fixes property in deduplication-api deployment
=> Fix mistake in deduplication-api deployment.yaml

.gitignore, argocd/Chart.yaml, argocd/README.md, argocd/templates/data-processing-service.yaml, argocd/templates/dataingestion-service.yaml, argocd/templates/debezium.yaml, argocd/templates/elasticsearch.yaml, argocd/templates/investigation-service.yaml, argocd/templates/job-wait.yaml, argocd/templates/kafka-sink-connector.yaml, argocd/templates/keycloak.yaml, argocd/templates/ldf-service.yaml, argocd/templates/liquibase.yaml, argocd/templates/modernization-api.yaml, argocd/templates/nbs-gateway.yaml, argocd/templates/nifi.yaml, argocd/templates/nnd-service.yaml, argocd/templates/observation-service.yaml, argocd/templates/organization-service.yaml, argocd/templates/page-builder.yaml, argocd/templates/person-service.yaml, argocd/templates/post-processing-service.yaml, argocd/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> Pv argo updates

charts/debezium/values-dts1.yaml, charts/debezium/values-feature.yaml, charts/debezium/values-int1.yaml, charts/debezium/values-test1.yaml
CNAT-450-rtr-debezium-connector-meta: Upgrade debezium rtr services to include the odse metadata connector in INT/TEST/FEATURE env
=>  CNAT-450-rtr-debezium-connector-meta: Upgrade debezium rtr services to include the odse metadata connector in INT/TEST/FEATURE env

charts/nifi-efs/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> 7.9.3.1 Patch Release

charts/post-processing-reporting-service/Chart.yaml, charts/post-processing-reporting-service/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> update image tag

charts/sas-linux/templates/cron.yaml
Add check against db and prints results. Will print errors if found followed by a ERROR: message.
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```    
4. values.yaml is annotated to include parameter description …
=> Sgz add sas db check

.github/workflows/create-github-draft-release.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> Added 3 new services

argocd/Chart.yaml, charts/data-processing-service/Chart.yaml, charts/dataingestion-service/Chart.yaml, charts/elasticsearch-efs/Chart.yaml, charts/investigation-reporting-service/Chart.yaml, charts/ldfdata-reporting-service/Chart.yaml, charts/liquibase/Chart.yaml, charts/modernization-api/Chart.yaml, charts/nbs-gateway/Chart.yaml, charts/nifi-efs/Chart.yaml, charts/nnd-service/Chart.yaml, charts/observation-reporting-service/Chart.yaml, charts/organization-reporting-service/Chart.yaml, charts/page-builder-api/Chart.yaml, charts/person-reporting-service/Chart.yaml, charts/post-processing-reporting-service/Chart.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> modify appVersion

argocd/Chart.yaml, argocd/values.yaml, charts/case-notification-service/Chart.yaml, charts/case-notification-service/values.yaml, charts/data-extraction-service/Chart.yaml, charts/data-extraction-service/values.yaml, charts/data-processing-service/Chart.yaml, charts/data-processing-service/values.yaml, charts/dataingestion-service/Chart.yaml, charts/dataingestion-service/values.yaml, charts/elasticsearch-efs/Chart.yaml, charts/investigation-reporting-service/Chart.yaml, charts/ldfdata-reporting-service/Chart.yaml, charts/liquibase/Chart.yaml, charts/modernization-api/Chart.yaml, charts/modernization-api/values.yaml, charts/nbs-gateway/Chart.yaml, charts/nbs-gateway/values.yaml, charts/nifi-efs/Chart.yaml, charts/nnd-service/Chart.yaml, charts/observation-reporting-service/Chart.yaml, charts/organization-reporting-service/Chart.yaml, charts/page-builder-api/Chart.yaml, charts/page-builder-api/values.yaml, charts/person-reporting-service/Chart.yaml, charts/post-processing-reporting-service/Chart.yaml, charts/xml-hl7-parser-service/Chart.yaml, charts/xml-hl7-parser-service/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> updated for 7.10.2 release

charts/case-notification-service/values-feature.yaml, charts/case-notification-service/values-int1.yaml, charts/case-notification-service/values-test2.yaml, charts/data-extraction-service/values-feature.yaml, charts/data-extraction-service/values-int1.yaml, charts/data-extraction-service/values-test2.yaml, charts/data-processing-service/values-dts1.yaml, charts/data-processing-service/values-feature.yaml, charts/data-processing-service/values-int1.yaml, charts/data-processing-service/values-test2.yaml, charts/nnd-service/values-feature.yaml, charts/nnd-service/values-int1.yaml, charts/nnd-service/values-test2.yaml, charts/xml-hl7-parser-service/values-feature.yaml, charts/xml-hl7-parser-service/values-int1.yaml, charts/xml-hl7-parser-service/values-test2.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> Image Update for 7.11.0

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/liquibase/values.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml, charts/rtr/values-dts1.yaml, charts/rtr/values-int1.yaml, charts/rtr/values-test.yaml
CNAT-509: RTR Pushing the latest tags c3d2909
=> CNAT-509: RTR Pushing the latest tags c3d2909 

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml, charts/rtr/values-dts1.yaml, charts/rtr/values-int1.yaml, charts/rtr/values-test.yaml, charts/rtr/values.yaml
CNAT-509: Update the  RTR release tag to `1df10b5`.
=> CNAT-509: Update the  RTR release tag to `1df10b5`.

charts/investigation-reporting-service/values-feature.yaml, charts/investigation-reporting-service/values-int1.yaml, charts/investigation-reporting-service/values-test1.yaml, charts/ldfdata-reporting-service/values-feature.yaml, charts/ldfdata-reporting-service/values-int1.yaml, charts/ldfdata-reporting-service/values-test1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/observation-reporting-service/values-feature.yaml, charts/observation-reporting-service/values-int1.yaml, charts/observation-reporting-service/values-test1.yaml, charts/organization-reporting-service/values-feature.yaml, charts/organization-reporting-service/values-int1.yaml, charts/organization-reporting-service/values-test1.yaml, charts/person-reporting-service/values-feature.yaml, charts/person-reporting-service/values-int1.yaml, charts/person-reporting-service/values-test1.yaml, charts/post-processing-reporting-service/values-feature.yaml, charts/post-processing-reporting-service/values-int1.yaml, charts/post-processing-reporting-service/values-test1.yaml, charts/rtr/values-dts1.yaml, charts/rtr/values-int1.yaml, charts/rtr/values-test.yaml, charts/rtr/values.yaml
CNAT-509: Update the  RTR release tag to `165bc00`.
=> CNAT-509: Update the  RTR release tag to `165bc00`.

charts/liquibase/values-dts1.yaml, charts/liquibase/values-feature.yaml, charts/liquibase/values-int1.yaml, charts/liquibase/values-test1.yaml, charts/liquibase/values.yaml
CNDE-2921-rtr-711-tag : Clean up the RTR liquibase values files
=> CNDE-2921-rtr-711-tag : Clean up the RTR liquibase values files

charts/debezium/templates/deployment.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> added liveness and readiness

k8-manifests/nbs-secrets.yaml
Update the RTR nbs-secrets.yaml secret name
=> Update the RTR nbs-secrets.yaml secret name

charts/modernization-api/values-int1.yaml
update tag and remove unneeded services section (not to be confused with service section)
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```    
3. **Do not include secret values anywhere in a …
=> Update values-int1.yaml to remove consolidated section

charts/rtr/templates/deployment.yaml, charts/rtr/values-dts1.yaml, charts/rtr/values.yaml
Update the RTR java services helm chart to account for the threadpool number
=> Update the RTR java services helm chart to account for the threadpool number

argocd/Chart.yaml, argocd/templates/rtr.yaml, argocd/values.yaml
```  
|── charts
├── templates
|   ├── tests
|   ├── *.yaml
└─  README.md
```     …
=> argocd updates 7.11.1
